### ISSUE TITLE
add more info in README on what this does

### ISSUE THREAD

**Issue by mesqueeb** [capacitor-community/media#14]
What I can gather from the readme:
> Capacitor community plugin for enabling extra media capabilities

and it can do stuff like
> savePhoto
> saveVideo

But it's not very clear right now if this relates to capturing photos/videos from the camera as well? 
"save photo" is such a vague term, what does it mean EXACTLY?

Is it like save a photo from a URL or from the iPhone/Android local storage? Or save a photo that you capture?

I'd love some extra information on what this plugin does exactly!

**Comment by mepc36** [comment]
+1 on @mesqueeb's request for more specification about what this package does, please!

More specifically, it's hard to tell...
- what kind of videos can be saved? (Do they already have to be on the photo roll? Where is the "path" argument being passed into .saveVideo coming from? What is an example of a valid path?) 
- whether this package can truly create a new resource in a phone's local photo roll as the term ".saveVideo()" implies, or whether it just copies an already-existing video from one place to another on the photo roll (because that's what the "path" parameter is telling me that this package does as of now).

I'm 100% sure some of these questions seem inane to the maintainers, but I'd imagine that for the typical user of a capacitor package like this — i.e., not trained in a native language — making their onboarding as easy as possible would be a huge help.

Thanks!
