### ISSUE TITLE
getMedias for android not implemented

### ISSUE THREAD

**Issue by simion** [capacitor-community/media#15]
**Describe the solution you'd like**
When do you plan to implement getMedias for Android? I'm building an app which needs to access all device photos, from
Recent album, and this feature is critical :)

**Additional context**
Meanwhile, could someone recommend a capacitor or cordova plugin which allowe access to all device photos? Thanks

**Comment by Hanho-Kim** [comment]
I just write rough code for my application, I hope this may help you.

Edit `MediaPlugin.java` located on "androd>src>main>java>com>getcapacitor>community>media>MediaPlugin.java",

```
@PluginMethod()
public void getMedias(PluginCall call) {
        Log.d("DEBUG LOG", "GET MEDIAS");
        if (hasPermission(Manifest.permission.READ_EXTERNAL_STORAGE)) {
            //call.unimplemented();
            Log.d("DEBUG LOG", "HAS PERMISSION");
            _getMedias(call);
        }else{
            Log.d("DEBUG LOG", "NOT ALLOWED");
            pluginRequestPermission(Manifest.permission.READ_EXTERNAL_STORAGE, 1986);
        }
}
```


with create new method named `_getMedias()`
```
    // @todo Add creationDate, fullWidth, fullHeight, thumbnailWidth, thumbnailHeight, location
    private void _getMedias(PluginCall call){
        JSObject response = new JSObject();
        JSArray assets = new JSArray();

        Uri uri = MediaStore.Images.Media.EXTERNAL_CONTENT_URI;

        String[] projection = {
                MediaStore.Images.Media._ID,
                MediaStore.Images.Media.DATA,
        };

        Cursor cursor = getActivity().getContentResolver().query(uri, projection, null, null, MediaStore.Images.Media._ID + " DESC");

        int columnIndexId = cursor.getColumnIndex(MediaStore.Images.Media._ID);
        int columnIndexURI = cursor.getColumnIndex(MediaStore.Images.Media.DATA);

        int start = call.getInt("start");

        int quantity = call.getInt("quantity");
        if(quantity == 0) quantity = 20;

        cursor.moveToPosition(start-1); // From Index
        while (cursor.moveToNext() && cursor.getPosition() < start + quantity) { // To Index
            JSObject asset = new JSObject();
            asset.put("identifier", cursor.getString(columnIndexId));
            asset.put("data", cursor.getString(columnIndexURI)); // return filepath, have to convert Capacitor.convertFileSrc() to use in HTML & Javascript
            assets.put(asset);
        }

        cursor.close();

        response.put("medias", assets);
        call.resolve(response);

    }
```

I added 'start' parameter on MediaAsset interface for pagination, if you don't need, you can omit it. (Default value will be set as 0, in other words, start from 0 index = same result as original plugin returns)

Since I couldn't find any fast solution to encode and return base64 just like iOS plugin do, I decided to return "data" value as external URI of media file. But Capacitor has great built-in javascript function to convert external URI to Webview accessible file path,

```
import { Capacitor } from '@capacitor/core';
...

media
  .getMedias({quantity:20, start: 10})
  .then(function(res){

    res.medias.forEach(function(media){
      console.log(Capacitor.convertFileSrc(media.data)); // This returns accessible media path on Webview
    });

  })
  .catch(console.log);

```

You can render media files on HTML!

Since I am not a Java developer, please let me know if there is any possibilities to improve the code.

**Comment by simion** [comment]
I've given up on this, learned flutter, and wrote my entire app using flutter, since they have awesome working plugins for everything :) 
4 months later, https://homestash.app/ was born.

**Comment by stewones** [comment]
can you have a try on v3?

**Comment by merbin2012** [comment]
Is there any update on this? Still I have the same problem, Capacitor 6

**Comment by stephan-fischer** [comment]
@nkalupahana  ist this feature is not planned forever or is there a chance to get this feature?
