### ISSUE TITLE
Media gets deleted when uninstalling app

### ISSUE THREAD

**Issue by ingojoseph** [capacitor-community/media#51]
I save photos with `Media.savePhoto(...)`. They show up in the album but when I uninstall the app, the album gets deleted. Is this the expected behavior and is there a way to disable it? (Using Android, not sure about iOS)

**Comment by nkalupahana** [comment]
Yes, this is expected behavior on Android, because albums are app-specific. The idea is that Google Photos should pick up these photos and sync them, so if the user wants the photos after the app is deleted, they should still be there. I'm not sure there's a way around this on Android (if you can something online that says otherwise, though, please share it!).

iOS does not delete photos after the app is deleted.

**Comment by ingojoseph** [comment]
@nkalupahana thanks a lot for the explanation!
